# Generated by Django 5.2.3 on 2025-08-29 14:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Maximum 280 characters', max_length=280, validators=[django.core.validators.MaxLengthValidator(280)])),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('announcement', 'Announcement'), ('question', 'Question')], default='general', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='posts_created_2e2442_idx'), models.Index(fields=['author', '-created_at'], name='posts_author__f2f966_idx'), models.Index(fields=['is_active', '-created_at'], name='posts_is_acti_e74456_idx')],
            },
        ),
    ]
