# Generated by Django 5.2.3 on 2025-08-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.TextField(blank=True, help_text='Image URL or base64 data', null=True),
        ),
    ]
